"""P5 Hermes gap: cross-session user-model refinement.

Deterministic extraction only — nothing is generated by a model, and no fact is
recorded unless the person actually said it in a recognised self-statement.
"""
from __future__ import annotations

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from core.db import Database                     # noqa: E402
from usermodel.service import (BASE_CONFIDENCE, MAX_CONFIDENCE,  # noqa: E402
                               UserModelService)


@pytest.fixture()
def db(tmp_path):
    return Database(tmp_path / "test.db")


@pytest.fixture()
def um(db):
    return UserModelService(db)


# --------------------------------------------------------------- extraction
def test_explicit_name_is_extracted(um):
    obs = um.extract("call me Ada")
    assert [o["trait"] for o in obs] == ["name"]
    assert obs[0]["value"] == "Ada"


def test_preference_is_extracted(um):
    obs = um.extract("I prefer dark mode")
    assert obs and obs[0]["trait"] == "preference"
    assert "dark mode" in obs[0]["value"]


def test_role_goal_language_aversion_are_extracted(um):
    assert any(o["trait"] == "role" for o in um.extract("I am a backend engineer"))
    assert any(o["trait"] == "goal" for o in um.extract("I want to ship GENIE"))
    assert any(o["trait"] == "language" for o in um.extract("I speak Hindi"))
    assert any(o["trait"] == "aversion" for o in um.extract("I dislike noisy alerts"))


def test_nothing_is_invented_from_ordinary_text(um):
    assert um.extract("what is the weather today") == []
    assert um.extract("") == []
    assert um.extract(None) == []


# ------------------------------------------------------------------ observe
def test_first_observation_starts_at_base_confidence(um):
    out = um.observe("p1", "name", "Ada", evidence="call me Ada")
    assert out["confidence"] == BASE_CONFIDENCE
    assert out["support"] == 1
    assert out["updated"] is False


def test_repeated_observation_raises_confidence(um):
    um.observe("p1", "preference", "dark mode")
    second = um.observe("p1", "preference", "dark mode")
    assert second["updated"] is True
    assert second["confidence"] > BASE_CONFIDENCE
    assert second["support"] == 2


def test_confidence_is_bounded(um):
    for _ in range(30):
        um.observe("p1", "preference", "dark mode")
    prof = um.profile("p1")
    assert prof["traits"]["preference"]["confidence"] <= MAX_CONFIDENCE


def test_conflicting_single_valued_trait_supersedes(um):
    um.observe("p1", "name", "Ada")
    um.observe("p1", "name", "Grace")
    prof = um.profile("p1")
    assert prof["traits"]["name"]["value"] == "Grace"
    active = um.facts("p1")
    assert [f["value"] for f in active] == ["Grace"]
    superseded = um.facts("p1", include_superseded=True)
    assert sorted(f["value"] for f in superseded) == ["Ada", "Grace"], \
        "the superseded value must be retained for audit, not erased"


def test_multi_valued_traits_coexist(um):
    um.observe("p1", "preference", "dark mode")
    um.observe("p1", "preference", "vim")
    assert len(um.facts("p1")) == 2


def test_observe_requires_identity_trait_and_value(um):
    for args in (("", "name", "Ada"), ("p1", "", "Ada"), ("p1", "name", "")):
        with pytest.raises(ValueError):
            um.observe(*args)


# ------------------------------------------------------ cross-session refine
def test_refine_from_text_records_every_statement(um):
    out = um.refine_from_text("p1", "call me Ada and I prefer dark mode")
    assert len(out) == 2


def test_refine_from_session_ignores_genie_turns(um):
    """GENIE's own replies are not evidence about the person."""
    history = [
        {"role": "user", "text": "call me Ada"},
        {"role": "genie", "text": "call me Zeta"},
    ]
    um.refine_from_session("p1", history, session_id="s1")
    assert um.profile("p1")["traits"]["name"]["value"] == "Ada"


def test_model_persists_across_sessions(um, db):
    """The Hermes idea: the model deepens across separate sessions."""
    um.refine_from_session("p1", [{"role": "user", "text": "call me Ada"}],
                           session_id="s1")
    um2 = UserModelService(db)                      # new session / restart
    um2.refine_from_session("p1", [{"role": "user", "text": "I prefer dark mode"}],
                            session_id="s2")
    prof = um2.profile("p1")
    assert "name" in prof["traits"]
    assert "preference" in prof["traits"]


def test_second_service_instance_sees_the_same_model(um, db):
    um.observe("p1", "name", "Ada")
    assert UserModelService(db).profile("p1")["traits"]["name"]["value"] == "Ada"


# ------------------------------------------------------------------ privacy
def test_forget_one_trait(um):
    um.observe("p1", "name", "Ada")
    um.observe("p1", "preference", "tea")
    um.forget("p1", trait="name")
    prof = um.profile("p1")
    assert "name" not in prof["traits"]
    assert "preference" in prof["traits"]


def test_forget_everything(um):
    um.observe("p1", "name", "Ada")
    um.forget("p1")
    assert um.profile("p1")["traits"] == {}


def test_profile_is_per_person(um):
    um.observe("p1", "name", "Ada")
    um.observe("p2", "name", "Grace")
    assert um.profile("p1")["traits"]["name"]["value"] == "Ada"
    assert um.profile("p2")["traits"]["name"]["value"] == "Grace"
